raw_output = "false"
user_token = ""

[filter]
  limit = "10"
  offset = "0"
  topic = ""

[remotes]
  bootstrap_url = "http://localhost:9013"
  certs_url = "http://localhost:9019"
  domains_url = "http://localhost:9003"
  host_url = "http://localhost"
  http_adapter_url = "http://localhost:8008"
  invitations_url = "http://localhost:9020"
  journal_url = "http://localhost:9021"
  reader_url = "http://localhost:9011"
  channels_url = "http://localhost:9005"
  clients_url = "http://localhost:9006"
  tls_verification = false
  users_url = "http://localhost:9002"
