#
# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0
#

copyright: Copyright (c) Abstract Machines
repo_url: https://github.com/absmach/magistrala
site_description: Magistrala IoT System
site_name: Magistrala
site_url: https://docs.magistrala.abstractmachines.fr
edit_uri: ""
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

plugins:
  - drawio_file

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: "#"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  # Core
  - Entities: entities.md
  - API: api.md
  - CLI: cli.md
  - Authentication: authentication.md
  - Authorization: authorization.md
  - Security: security.md
  - Messaging: messaging.md
  - Events: events.md
  # Edge
  - Edge: edge.md
  # Addons
  - Certs: certs.md
  - Bootstrap: bootstrap.md
  - LoRa: lora.md
  - OPC-UA: opcua.md
  - Provision: provision.md
  - Storage: storage.md
  - Twins: twins.md
  # Observability
  - Tracing: tracing.md
  # Utilities
  - Developer's Guide: dev-guide.md
  - Kubernetes: kubernetes.md
  - Benchmark: benchmark.md
