blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ GitHub Issues
    url: https://github.com/absmach/magistrala-docs/issues
    about: If you have questions or found an issue, please file it here.
  - name: ğŸ› ï¸ Support
    url: mailto:support@absmach.eu
    about: If you need help or have a support request, reach out to us directly.
